### PR TITLE
fix file extension error in phylogenetics package

### PR DESCRIPTION
**Pull request by lcwheeler**
Add catches for variation in the file extensions of phyml output files.

### CODE REVIEW

**Comment by lcwheeler** [comment]
Hey Zach! I think this fixes the problem. Just added a try/except clause that seems to take care of the issue.

**Comment by Zsailer** [comment]
This works actually. We'll pull directly from your `patch` branch. Don't merge into your master first. 

Once these changes land here on the master branch, pull the changes to your local branch and push them to your remote master.

**Comment by Zsailer** [comment]
Thanks for working on this!

**Comment by lcwheeler** [comment]
Awesome! No problem! Glad I could help a little. I'll make sure you get the pushing and pulling right next time, haha.

**Comment by Zsailer** [comment]
Haha no problem at all! Github takes some time to get used to. No one can be upset when you're offering your help! 😄 

If you get an error when pull these changes to your fork on Github (because it includes your `patch` merge) just use the `-f` flag. This may be the only time you should ever do that. 😉

**Comment by Zsailer** [comment]
If you find any more bugs or want to add examples/docs, feel free to submit more PRs! It's really helpful. I'll be working on this repo once if my recent SciPy proposal is accepted ("Resurrecting ancient proteins in Python")

**Comment by lcwheeler** [comment]
Cool, sounds good! I'll let you know if I find any more bugs. Good luck on getting the SciPy proposal accepted! :)

**Pull request merged**
